[advisories]
version = 2
db-path = ".advisory-db"
yanked = "deny"

[licenses]
version = 2
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Unicode-DFS-2016",
]

[licenses.private]
ignore = false
registries = [
]
