all-features = true

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

[licenses]
unlicensed = "deny"
allow = [
    "Unicode-DFS-2016",
]
copyleft = "warn"
allow-osi-fsf-free = "both"
default = "deny"

[licenses.private]
ignore = false
registries = [
]
